/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 22-oct.-2023 10:32:06 p. m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Certificado" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Contacto" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Desarrollador" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Habilidad" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "HabilidadProyectos" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Persona" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Proyecto" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

/* Create Tables */

CREATE TABLE  "Certificado"
(
	"K_CODIGO" NUMBER(8) NOT NULL,
	"K_ID" NUMBER(3) NOT NULL,
	"N_NOMBRE_TITULO" VARCHAR2(150) NOT NULL,
	"F_FECHA_REALIZACION" DATE NOT NULL,
	"I_TIPO" CHAR(2) NOT NULL,
	"N_ENTIDAD_CERTIFICA" VARCHAR2(50) NOT NULL
)
;

CREATE TABLE  "Contacto"
(
	"K_ID" NUMBER(3) NOT NULL,
	"N_MENSAJE" VARCHAR2(500) NOT NULL
)
;

CREATE TABLE  "Desarrollador"
(
	"K_ID" NUMBER(3) NOT NULL,
	"N_BIOGRAFIA" VARCHAR2(500) NOT NULL,
	"L_REDES_ENLACES" VARCHAR2(250) NOT NULL,
	"Q_AÑOS_EXPERIENCIA" NUMBER(2) NOT NULL
)
;

CREATE TABLE  "Habilidad"
(
	"K_ID_HABILIDAD" NUMBER(2) NOT NULL,
	"K_ID" NUMBER(3) NOT NULL,
	"N_NOMBRE_TECNOLOGIA" VARCHAR2(50) NOT NULL,
	"I_TIPO" CHAR(2) NOT NULL,
	"T_DESTREZA" NUMBER(3,2) NOT NULL
)
;

CREATE TABLE  "HabilidadProyectos"
(
	"K_ID_HABILIDAD" NUMBER(2) NOT NULL,
	"K_ID_PROYECTO" NUMBER(2) NOT NULL
)
;

CREATE TABLE  "Persona"
(
	"K_ID" NUMBER(3) NOT NULL,
	"N_NOMBRE" VARCHAR2(50) NOT NULL,
	"N_CORREO" VARCHAR2(50) NOT NULL,
	"Q_TELEFONO" NUMBER(10) NULL
)
;

CREATE TABLE  "Proyecto"
(
	"K_ID_PROYECTO" NUMBER(2) NOT NULL,
	"K_ID" NUMBER(3) NOT NULL,
	"N_NOMBRE" VARCHAR2(100) NOT NULL,
	"N_DESCRIPCION" VARCHAR2(500) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "Certificado" 
 ADD CONSTRAINT "PK_Certificado"
	PRIMARY KEY ("K_CODIGO") 
 USING INDEX
;

CREATE INDEX "IXFK_Certificado_Desarrollador"   
 ON  "Certificado" ("K_ID") 
;

ALTER TABLE  "Contacto" 
 ADD CONSTRAINT "PK_Contacto"
	PRIMARY KEY ("K_ID") 
 USING INDEX
;

CREATE INDEX "IXFK_Contacto_Persona"   
 ON  "Contacto" ("K_ID") 
;

ALTER TABLE  "Desarrollador" 
 ADD CONSTRAINT "PK_Desarrollador"
	PRIMARY KEY ("K_ID") 
 USING INDEX
;

CREATE INDEX "IXFK_Desarrollador_Persona"   
 ON  "Desarrollador" ("K_ID") 
;

ALTER TABLE  "Habilidad" 
 ADD CONSTRAINT "PK_Habilidad"
	PRIMARY KEY ("K_ID_HABILIDAD") 
 USING INDEX
;

CREATE INDEX "IXFK_Habilidad_Desarrollador"   
 ON  "Habilidad" ("K_ID") 
;

ALTER TABLE  "HabilidadProyectos" 
 ADD CONSTRAINT "PK_HabilidadPro_01"
	PRIMARY KEY ("K_ID_HABILIDAD","K_ID_PROYECTO") 
 USING INDEX
;

CREATE INDEX "IXFK_HabilidadProye_Habil01"   
 ON  "HabilidadProyectos" ("K_ID_HABILIDAD") 
;

CREATE INDEX "IXFK_HabilidadProyectos_P01"   
 ON  "HabilidadProyectos" ("K_ID_PROYECTO") 
;

ALTER TABLE  "Persona" 
 ADD CONSTRAINT "PK_Persona"
	PRIMARY KEY ("K_ID") 
 USING INDEX
;

ALTER TABLE  "Proyecto" 
 ADD CONSTRAINT "PK_Proyecto"
	PRIMARY KEY ("K_ID_PROYECTO") 
 USING INDEX
;

CREATE INDEX "IXFK_Proyecto_Desarrollador"   
 ON  "Proyecto" ("K_ID") 
;

/* Create Foreign Key Constraints */

ALTER TABLE  "Certificado" 
 ADD CONSTRAINT "FK_Certificado_Desarrollador"
	FOREIGN KEY ("K_ID") REFERENCES  "Desarrollador" ("K_ID")
;

ALTER TABLE  "Contacto" 
 ADD CONSTRAINT "FK_Contacto_Persona"
	FOREIGN KEY ("K_ID") REFERENCES  "Persona" ("K_ID")
;

ALTER TABLE  "Desarrollador" 
 ADD CONSTRAINT "FK_Desarrollador_Persona"
	FOREIGN KEY ("K_ID") REFERENCES  "Persona" ("K_ID")
;

ALTER TABLE  "Habilidad" 
 ADD CONSTRAINT "FK_Habilidad_Desarrollador"
	FOREIGN KEY ("K_ID") REFERENCES  "Desarrollador" ("K_ID")
;

ALTER TABLE  "HabilidadProyectos" 
 ADD CONSTRAINT "FK_HabilidadProye_Habilidad_01"
	FOREIGN KEY ("K_ID_HABILIDAD") REFERENCES  "Habilidad" ("K_ID_HABILIDAD")
;

ALTER TABLE  "HabilidadProyectos" 
 ADD CONSTRAINT "FK_HabilidadProyectos_Proyecto"
	FOREIGN KEY ("K_ID_PROYECTO") REFERENCES  "Proyecto" ("K_ID_PROYECTO")
;

ALTER TABLE  "Proyecto" 
 ADD CONSTRAINT "FK_Proyecto_Desarrollador"
	FOREIGN KEY ("K_ID") REFERENCES  "Desarrollador" ("K_ID")
;
